import * as React from "react"

/**
 * Properties for configuring toast appearance and behavior.
 */
export type ToastProps = {
  /** Whether the toast is currently open */
  open?: boolean
  /** Callback fired when open state changes */
  onOpenChange?: (open: boolean) => void
  /** Visual variant of the toast */
  variant?: "default" | "destructive"
}

/**
 * Action element to display in the toast (typically a button).
 */
export type ToastActionElement = React.ReactElement

/**
 * Maximum number of toasts to display simultaneously.
 * When limit is reached, oldest toasts are removed.
 */
const TOAST_LIMIT = 1

/**
 * Delay in milliseconds before removing a dismissed toast from memory.
 * This allows exit animations to complete before unmounting.
 *
 * Current value: 1000000ms (16.7 minutes) - likely for debugging.
 * Production value should typically be 3000-5000ms (3-5 seconds).
 */
const TOAST_REMOVE_DELAY = 1000000

/**
 * Complete toast object with all properties including generated ID.
 * This is what gets stored in state and passed to toast components.
 */
export type ToasterToast = ToastProps & {
  /** Unique identifier generated by genId() */
  id: string
  /** Main heading text of the toast */
  title?: React.ReactNode
  /** Secondary descriptive text */
  description?: React.ReactNode
  /** Optional action button or element */
  action?: ToastActionElement
}

const actionTypes = {
  ADD_TOAST: "ADD_TOAST",
  UPDATE_TOAST: "UPDATE_TOAST",
  DISMISS_TOAST: "DISMISS_TOAST",
  REMOVE_TOAST: "REMOVE_TOAST",
} as const

let count = 0

function genId() {
  count = (count + 1) % Number.MAX_SAFE_INTEGER
  return count.toString()
}

type ActionType = typeof actionTypes

type Action =
  | {
      type: ActionType["ADD_TOAST"]
      toast: ToasterToast
    }
  | {
      type: ActionType["UPDATE_TOAST"]
      toast: Partial<ToasterToast>
    }
  | {
      type: ActionType["DISMISS_TOAST"]
      toastId?: ToasterToast["id"]
    }
  | {
      type: ActionType["REMOVE_TOAST"]
      toastId?: ToasterToast["id"]
    }

interface State {
  toasts: ToasterToast[]
}

/**
 * Global map storing pending removal timeouts for each toast.
 * Key: toast ID, Value: setTimeout handle
 *
 * Why global? Timeouts need to persist across component re-renders and
 * need to be accessible from the reducer for cleanup.
 */
const toastTimeouts = new Map<string, ReturnType<typeof setTimeout>>()

/**
 * Schedule a toast for removal after TOAST_REMOVE_DELAY.
 *
 * This gives exit animations time to complete before unmounting the toast.
 * If a toast is already in the removal queue, this is a no-op.
 *
 * @param toastId - The ID of the toast to schedule for removal
 */
const addToRemoveQueue = (toastId: string) => {
  if (toastTimeouts.has(toastId)) {
    return
  }

  const timeout = setTimeout(() => {
    toastTimeouts.delete(toastId)
    dispatch({
      type: "REMOVE_TOAST",
      toastId: toastId,
    })
  }, TOAST_REMOVE_DELAY)

  toastTimeouts.set(toastId, timeout)
}

/**
 * State reducer for toast management.
 *
 * Handles four action types:
 * - ADD_TOAST: Add new toast (enforces TOAST_LIMIT)
 * - UPDATE_TOAST: Update existing toast properties
 * - DISMISS_TOAST: Mark toast(s) as closed and schedule removal
 * - REMOVE_TOAST: Remove toast(s) from state and clean up timeouts
 *
 * Note: DISMISS_TOAST contains side effects (addToRemoveQueue).
 * This is intentional for simplicity - could be extracted to middleware.
 *
 * @param state - Current toast state
 * @param action - Action to dispatch
 * @returns New state after applying action
 */
export const reducer = (state: State, action: Action): State => {
  switch (action.type) {
    case "ADD_TOAST":
      return {
        ...state,
        toasts: [action.toast, ...state.toasts].slice(0, TOAST_LIMIT),
      }

    case "UPDATE_TOAST":
      return {
        ...state,
        toasts: state.toasts.map((t) =>
          t.id === action.toast.id ? { ...t, ...action.toast } : t
        ),
      }

    case "DISMISS_TOAST": {
      const { toastId } = action

      // ! Side effects ! - This could be extracted into a dismissToast() action,
      // but I'll keep it here for simplicity
      if (toastId) {
        addToRemoveQueue(toastId)
      } else {
        state.toasts.forEach((toast) => {
          addToRemoveQueue(toast.id)
        })
      }

      return {
        ...state,
        toasts: state.toasts.map((t) =>
          t.id === toastId || toastId === undefined
            ? {
                ...t,
                open: false,
              }
            : t
        ),
      }
    }
    case "REMOVE_TOAST": {
      if (action.toastId === undefined) {
        // Remove all toasts - clean up all pending timeouts
        state.toasts.forEach((toast) => {
          const timeout = toastTimeouts.get(toast.id)
          if (timeout) {
            clearTimeout(timeout)
            toastTimeouts.delete(toast.id)
          }
        })
        return {
          ...state,
          toasts: [],
        }
      }
      // Remove specific toast - clean up its timeout if exists
      const timeout = toastTimeouts.get(action.toastId)
      if (timeout) {
        clearTimeout(timeout)
        toastTimeouts.delete(action.toastId)
      }
      return {
        ...state,
        toasts: state.toasts.filter((t) => t.id !== action.toastId),
      }
    }
  }
}

/**
 * Global listener registry.
 * Each component using useToast() registers its setState function here.
 *
 * Why array instead of Set? We need indexOf() for cleanup, and listeners
 * are added/removed infrequently (only on mount/unmount).
 */
const listeners: Array<(state: State) => void> = []

/**
 * Global toast state stored outside React.
 *
 * Why module-level state? Toast notifications often need to be triggered from:
 * - API error handlers (outside React)
 * - Event listeners (outside component tree)
 * - Utility functions (no access to Context)
 *
 * This pattern allows calling toast() from anywhere in the app.
 */
let memoryState: State = { toasts: [] }

/**
 * Dispatch an action to update global toast state.
 *
 * This updates memoryState and notifies all subscribed components.
 * All components using useToast() will re-render with the new state.
 *
 * @param action - The action to dispatch
 */
function dispatch(action: Action) {
  memoryState = reducer(memoryState, action)
  listeners.forEach((listener) => {
    listener(memoryState)
  })
}

type Toast = Omit<ToasterToast, "id">

/**
 * Create and display a toast notification.
 *
 * This function can be called from anywhere in your application, even outside
 * React components. The toast will be displayed in all mounted <Toaster />
 * components and will automatically manage its lifecycle.
 *
 * **How it works:**
 * 1. Generates unique ID for the toast
 * 2. Dispatches ADD_TOAST action to global state
 * 3. All components using useToast() re-render with new toast
 * 4. Returns control methods (dismiss, update)
 *
 * **Use cases:**
 * - Success/error notifications after API calls
 * - Form validation feedback
 * - System notifications (e.g., "Connection lost")
 * - Undo actions with action buttons
 *
 * @param props - Toast configuration (title, description, variant, action)
 * @returns Object with id, dismiss(), and update() methods
 *
 * @example
 * Basic success toast
 * ```tsx
 * import { toast } from '@/hooks/use-toast';
 *
 * function handleSave() {
 *   // ... save logic
 *   toast({
 *     title: "Success!",
 *     description: "Your changes have been saved.",
 *   });
 * }
 * ```
 *
 * @example
 * Error toast from API handler (outside React)
 * ```tsx
 * // api.ts
 * import { toast } from '@/hooks/use-toast';
 *
 * async function fetchData() {
 *   try {
 *     const res = await fetch('/api/data');
 *     if (!res.ok) throw new Error('Failed to fetch');
 *     return res.json();
 *   } catch (error) {
 *     toast({
 *       variant: "destructive",
 *       title: "Error",
 *       description: error.message,
 *     });
 *   }
 * }
 * ```
 *
 * @example
 * Toast with action button and manual control
 * ```tsx
 * function handleDelete() {
 *   const toastInstance = toast({
 *     title: "Item deleted",
 *     description: "The item has been moved to trash.",
 *     action: <button onClick={() => handleUndo()}>Undo</button>,
 *   });
 *
 *   // Manually dismiss after 5 seconds
 *   setTimeout(() => toastInstance.dismiss(), 5000);
 *
 *   // Or update the toast
 *   setTimeout(() => {
 *     toastInstance.update({
 *       title: "Permanently deleted",
 *       description: "The item cannot be recovered.",
 *     });
 *   }, 10000);
 * }
 * ```
 */
function toast({ ...props }: Toast) {
  const id = genId()

  const update = (props: ToasterToast) =>
    dispatch({
      type: "UPDATE_TOAST",
      toast: { ...props, id },
    })
  const dismiss = () => dispatch({ type: "DISMISS_TOAST", toastId: id })

  dispatch({
    type: "ADD_TOAST",
    toast: {
      ...props,
      id,
      open: true,
      onOpenChange: (open) => {
        if (!open) dismiss()
      },
    },
  })

  return {
    id: id,
    dismiss,
    update,
  }
}

/**
 * Hook to access toast state and trigger notifications from components.
 *
 * This hook subscribes to the global toast state and provides methods to
 * create and dismiss toasts. Use this in your Toaster component to render
 * active toasts, or in any component that needs to trigger notifications.
 *
 * **Architecture:**
 * - Uses module-level state (not Context) for maximum flexibility
 * - Allows toast() to be called from anywhere (even outside React)
 * - All components using useToast() share the same global state
 * - Automatically cleans up subscription on unmount
 *
 * **Use cases:**
 * - In <Toaster /> component to render active toasts
 * - In components that need to trigger toasts on user actions
 * - Accessing current toast state for conditional rendering
 *
 * @returns Object with:
 *   - toasts: Array of active toast objects
 *   - toast: Function to create new toast
 *   - dismiss: Function to dismiss toast(s)
 *
 * @example
 * Toaster component that renders toasts
 * ```tsx
 * import { useToast } from '@/hooks/use-toast';
 * import { Toast } from '@/components/ui/toast';
 *
 * export function Toaster() {
 *   const { toasts } = useToast();
 *
 *   return (
 *     <div className="toaster">
 *       {toasts.map((toast) => (
 *         <Toast key={toast.id} {...toast} />
 *       ))}
 *     </div>
 *   );
 * }
 * ```
 *
 * @example
 * Using toast in a component
 * ```tsx
 * import { useToast } from '@/hooks/use-toast';
 *
 * function MyComponent() {
 *   const { toast, dismiss } = useToast();
 *
 *   const handleSubmit = async () => {
 *     try {
 *       await submitForm();
 *       toast({
 *         title: "Success!",
 *         description: "Form submitted successfully.",
 *       });
 *     } catch (error) {
 *       toast({
 *         variant: "destructive",
 *         title: "Error",
 *         description: error.message,
 *       });
 *     }
 *   };
 *
 *   return (
 *     <div>
 *       <button onClick={handleSubmit}>Submit</button>
 *       <button onClick={() => dismiss()}>Dismiss all</button>
 *     </div>
 *   );
 * }
 * ```
 *
 * @example
 * Accessing toast state for conditional rendering
 * ```tsx
 * function StatusIndicator() {
 *   const { toasts } = useToast();
 *   const hasErrors = toasts.some(t => t.variant === 'destructive');
 *
 *   return (
 *     <div className={hasErrors ? 'error-state' : 'normal-state'}>
 *       {toasts.length} active notification{toasts.length !== 1 ? 's' : ''}
 *     </div>
 *   );
 * }
 * ```
 */
function useToast() {
  const [state, setState] = React.useState<State>(memoryState)

  /**
   * Subscribe to global toast state changes.
   *
   * Why no dependencies? This effect should only run on mount/unmount.
   * Adding `state` to deps would cause re-subscription on every state change,
   * creating duplicate listeners and performance issues.
   *
   * Why global state? Toast notifications often need to be triggered from
   * outside React (e.g., API error handlers), so we use module-level state
   * with a listener pattern instead of Context API.
   */
  React.useEffect(() => {
    listeners.push(setState)
    return () => {
      const index = listeners.indexOf(setState)
      if (index > -1) {
        listeners.splice(index, 1)
      }
    }
  }, []) // ✓ FIXED: Removed [state] to prevent infinite re-subscription

  return {
    ...state,
    toast,
    dismiss: (toastId?: string) => dispatch({ type: "DISMISS_TOAST", toastId }),
  }
}

export { useToast, toast }
